<?php include "funkcije.php" ?>
<DIV class="system-nav clearfix">
	<UL class="system-nav-list">
	  <LI><A href="index.php">Naslovna</A></LI>
	  <LI class="last"><A href="http://10.1.4.15" target="new">Webmail</A></LI>
	</UL>
</DIV>
<DIV id="wrapper" class="clearfix">
<DIV id="wrapper-inner">
<DIV id="header" class="clearfix">
<DIV>
	<table><tr valign="middle">
				<td><A href="index.php"><IMG alt="" src="img/logo_alfa.jpg" width="250" height="50"></A> </td>
				<td>&nbsp;</td>
				<td><span style="padding-left:20px; font-size:95"><strong><font size="6">Dobrodošli na portal</font></strong></span></td>
			</tr>		
	</table>		
</DIV>