<?php include "funkcije.php" ?>
<DIV class="system-nav clearfix">
	<UL class="system-nav-list">
	  <LI><A href="index.php">Naslovna</A></LI>
	</UL>
</DIV>
<DIV id="wrapper" class="clearfix">
<DIV id="wrapper-inner">
<DIV id="header" class="clearfix">
<DIV>
	<table><tr valign="middle">
				<td><A href="index.php"><IMG alt="" src="img/logo_alfa.jpg" width="288" height="40"></A> </td>
				<td>&nbsp;</td>
				<td><span style="padding-left:20px;"><span style="font-size:50px;">Dobrodošli na portal</span></span></td>
			</tr>		
	</table>		
</DIV>