<DIV id="smoothmenu1" class="ddsmoothmenu">
<ul>

<li><a href="#">Alfa-Plam</a>
  <ul>
  <li><a href="template_opsti.php?kategorija=misija">Misija i vizija</a></li>
  <li><a href="template_opsti.php?kategorija=podaci">Podaci</a></li>
  </ul>
</li>

<li><a href="index.php">Obaveštenja</a>
  <ul>
  <li><a href="template_info.php?kategorija=korporativna">Korporativna</a></li>
  <li><a href="template_info.php?kategorija=ostalo">Ostalo</a></li>  
  </ul>
</li>

<li><a href="#">Službena dokumenta</a>
  <ul>
  <li><a href="template_opsti.php?kategorija=orgseme">Organizacione šeme</a></li>
  <li>
	<a href="#">ISO standard</a>
	<ul>
		<li><a href="template_opsti.php?kategorija=iso_poslovnik">Poslovnik o kvalitetu</a></li>
		<li><a href="template_opsti.php?kategorija=iso_procedure">Procedure kvaliteta</a></li>
		<li><a href="template_opsti.php?kategorija=iso_uputstva">Radna uputstva</a></li>		
	</ul>
  </li>
  <li><a href="template_opsti.php?kategorija=pravilnici">Ugovori i pravilnici</a></li>  
  <li><a href="template_opsti.php?kategorija=bezbednost">Bezbednost i zaštita na radu</a></li>
  <li><a href="template_opsti.php?kategorija=obrasci">Obrasci</a></li>
  <li><a href="template_opsti.php?kategorija=sabloni">Šabloni</a></li>
  </ul>
</li>

<li><a href="#">Vremena</a>
  <ul>
  <li><a href="template_opsti.php?kategorija=radnovreme">Radno vreme</a></li>
  <li><a href="template_opsti.php?kategorija=radnovremerestoran">Raspored korišćenja toplog obroka u restoranu</a></li>
  <li><a href="template_opsti.php?kategorija=radnovremepauza">Raspored korišćenja pauze</a></li>  
  </ul>
</li>

<li><a href="imenici.php">Imenici</a></li>

<li><a href="#">Kalendari</a>
  <ul>
  <li><a href="template_opsti.php?kategorija=kalendar">Poslovni kalendari</a></li>
  </ul>
</li>

<li><a href="#">Servisne informacije</a>
  <ul>
	  <li><a href="template_opsti.php?kategorija=jelovnik">Jelovnik</a></li>  
	  <li><a href="#">Dežurstvo vozila za hitne slučajeve</a></li>  	  
  </ul>
</li>

<li><a href="#">Razno</a>
  <ul>
  <li><a href="template_misli.php">Misli</a></li>
  <li><a href="template_opsti.php?kategorija=saveti">Korisni saveti</a></li>
  </ul>
</li>

</ul>
<br style="clear: left" />
</div>
</DIV>