<DIV id="calendar_box"><A class="title" href="kalendar.php">Kalendar</A></DIV>

<DIV id="kalendar" style="margin:10px 0 30px 0; border: 0px red; width:190px; height:200px;"> </DIV>

<DIV id="quick_links">
<H2>Brzi linkovi</H2>
	<UL>
	  <LI><A href="template_info.php?kategorija=korporativna">Korporativna obaveštenja</A></LI>
	  <LI><A href="template_opsti.php?kategorija=orgseme">Organizacione šeme</A></LI>
	  <LI><A href="template_opsti.php?kategorija=obrasci">Obrasci</A></LI>
	  <LI><A href="upload_login.php">Razmena fajlova</A></LI>

	</UL>
</DIV>

</DIV>